### ISSUE TITLE
Dependencies' old node dependencies need to be updated

### ISSUE THREAD

**Issue by stucka** [palewire/install-python-pipenv-pipfile#9]
I found a Node 12 (!) dependency and believe I've cleared that.

There's at least one Node 16 dependency I'm hoping will be patched soon.

https://github.com/palewire/install-python-pipenv-pipfile/pull/8

**Comment by palewire** [comment]
How we doing now?

**Comment by stucka** [comment]
Ack! I'd thought I'd dropped this as an issue in bln-python-client -- will test there.

**Comment by stucka** [comment]
@palewire , still having a problem because we're using "@v3" but the v3 tag hasn't been updated and v4 hasn't been issued. I can point to a specific hash and be OK though if you want me to go that route.

**Comment by stucka** [comment]
Just did another pull request because the other patch yesterday introduced a new Node 16 dependency =)

**Comment by stucka** [comment]
This one https://github.com/palewire/install-python-pipenv-pipfile/pull/10

**Comment by palewire** [comment]
Okay. Better?

**Comment by stucka** [comment]
Thank you! References to 21613f77896f538a9e83e8cf40ecd2c739a03549 should be fine now, if people want to go that way they'll have the Node 20 versions complete. The "V3" tag is pointing at an older version; don't know if you want to do a new release.

I'm good by pointing to the SHA, so it's entirely up to you. =)

**Comment by palewire** [comment]
I think I've released v4. Let me know how it goes.

**Comment by stucka** [comment]
You are a scholar and a gentleman, @palewire . Thank you!
